<a href="https://colab.research.google.com/github/KwonHo-geun/automobile/blob/main/25.07.02%20-%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

07.02일자

Numpy - Dimension

In [39]:
import numpy

arr = numpy.array([1,2,3,4,5])

print(type(arr))
print(arr)

#np로 이름 바꾸기
import numpy as np

arr1 = np.array([5,6,7,8,9])
print(type(arr1))
print(arr1)

#numpy version 확인
print(np.__version__)

#numpy 배열 차원
#0차원
arr2 = np.array(43)
print(arr2)

#1차원
arr3 = np.array([10,11,12,13,14])
print(arr3)

#2차원
arr4 = np.array([[15,25,35], [45,55,65]])
print(arr4)

#3차원
arr5 = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])
print(arr5)

#차원 확인하기
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)

#ndim으로 고차원 배열 받기 가능
arr6 = np.array([1,2,3,4,5], ndmin=5)
print(arr6)
print('number of dimensions :', arr5.ndim)

<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[5 6 7 8 9]
2.0.2
43
[10 11 12 13 14]
[[15 25 35]
 [45 55 65]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3
[[[[[1 2 3 4 5]]]]]
number of dimensions : 3


Numpy - Array Indexing

In [52]:
#array와 동일하게 index가 0부터 시작
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

#2D Array의 경우 - 0,1,2,3,4... 순으로 돌아감
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row :', arr2[0,1])
print('2nd element on 1st row :', arr2[1,4])

#3D Array의 경우
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#0은 [1,2,3],[4,5,6]을 뜻하고, 1은 그중 [4,5,6]을 뜻함 이유는 두개의 배열도 0,1,2...이런식이기 때문
#마지막으로 2는 [4,5,6]에서 6을 뜻함
print(arr3[0,1,2])

#여기서 배열의 0,1 두개 중 1번에서 마지막번째를 얻는다는 것
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim :', arr4[1, -1])



1
2
7
2nd element on 1st row : 2
2nd element on 1st row : 10
6
Last element from 2nd dim : 10


Numpy - Array Slicing

In [65]:
#Array의 element를 가져온다는 것
import numpy as np

arr = np.array([1,2,3,4,5,6,7])
#element 1부터 5번미만 즉, 2,3,4,5까지. 마지막 6은 제외한다.
print(arr[1:5])
print(arr[4:])
print(arr[:4])

#반대 Slicing - 여기선 첫번재 element인 4를 제외한다. 정반대
arr1 = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

#step - 단계를 결정하는 것. - 아래는 2,3번째 element만 출력
arr2 = np.array([1,2,3,4,5,6,7])
print(arr2[1:5:2])
print(arr2[::2])
print(arr2[::3])

#Slicing 2D Arrays - 아래는 2D Array의 1 element 중 1~4 element 출력
arr3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr3[1, 1:4])
# 두개의 배열에서 index 2번째 element 출력
print(arr3[0:2, 2])
# 두개의 배열에서 index 1~4번째까 element 출력
print(arr3[0:2, 1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[1 4 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


Numpy - Data Types

In [75]:
import numpy as np

arr =  np.array([1,2,3,4])
print(arr.dtype)

arr1 = np.array(['apple', 'banana', 'cherry'])
print(arr1.dtype)

#Createing Arrays With a Defined Data Type
#String
arr2 = np.array([1,2,3,4], dtype='S')
print(arr2)
print(arr2.dtype)

#int32
arr3 = np.array([1,2,3,4], dtype = 'i4')
print(arr3)
print(arr3.dtype)

#arr = np.array(['a','2','3'], dtype = 'i') - a는 정수형이 아닌 문자열이기에 불가

#Converting Data Type on Existing Arrays - 데이터 유형 변환
arr4 = np.array([1.1, 2.1, 3.1])
print(type(arr4))
newarr = arr4.astype('i')
newarr1 = arr4.astype(int)
print(newarr)
print(newarr.dtype)
print(newarr1)
print(newarr1.dtype)

arr5 = np.array([1,0,3])
newarr2 = arr5.astype(bool)
print(newarr2)
print(newarr2.dtype)



int64
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
<class 'numpy.ndarray'>
[1 2 3]
int32
[1 2 3]
int64
[ True False  True]
bool


Numpy - Array Copy vs View

In [78]:
#Copy는 새로운 Array, view는 원래 Array
import numpy as np

#Copy
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] =43
print(arr)
print(x)

#View - 오리지널이랑 똑같음.
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

#base - 원래 Copy or View를 한 데이터가 뭔지 참조하는 것
arr1 = np.array([6,7,8,9])
#새로운 애라 없음 - None
x = arr1.copy()
#원본이 있으니 참조가
y = arr1.view()

print(x.base)
print(y.base)

[43  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[6 7 8 9]


Numpy - Array Shape

In [81]:
#속성을 튜플로 반환
import numpy as np
#2개의 dimension, 각 dimension의 elements는 4
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

#5 dimension, 4번째의 5개의 elements
arr1 = np.array([1,2,3,4,5], ndmin = 5)
print(arr1)
print('shape of array :', arr1.shape)

(2, 4)
[[[[[1 2 3 4 5]]]]]
shape of array : (1, 1, 1, 1, 5)


Numpy - Reshaping Arrays

In [91]:
#배열의 모양을 바꿈
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

#1D -> 2D Array로 바꾸고, 1. 4개의 array, 2. 3개의 elements로 바꿈
newarr = arr.reshape(4,3)
print(newarr)

#1D -> 3D Array로 바꿈 3 array, 2 elements
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr1 = arr1.reshape(2,3,2)
print(newarr1)

#elements 사이즈에 알맞는 reshape를 하지 않으면 오류가 발생함.
"""
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)
"""

#Copy, View도 가능
arr2 = np.array([1,2,3,4,5,6,7,8])
newarr2 = arr2.copy()
newarr3 = arr2.view()
print(newarr2.base)
print(newarr3.base)

print(arr2.reshape(2,4).base)

#Unknown Dimension 중간에 알수없는 차원이 하나있음. 비어있는
arr3 = np.array([1,2,3,4,5,6,7,8])
newarr3 = arr3.reshape(2,2,-1)
print(newarr3)

#Flattening - 평탄화. 즉 1D로 바꾸는것
arr4 = np.array([[1,2,3],[4,5,6]])
newarr4 = arr4.reshape(-1)
print(newarr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
None
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]


Numpy - Array Iterating

In [99]:
#반복
import numpy as np

arr = np.array([1,2,3])

for x in arr:
  print(x)

arr1 = np.array([[1,2,3],[4,5,6]])

for x in arr1:
  print(x)

#2D = 1번째 반복문 - 배열 갯수, 2번째 반복문 배열 내 elements 반
for y in arr1:
  for z in y:
    print(z)

arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr2:
  print(x)

for x in arr2:
  for y in x:
    print(y)

for x in arr2:
  for y in x:
    for z in y:
      print(z)

#Iterating Arrays Using nditer() -

1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12
